### ISSUE TITLE
Post script ideas on Figma Board

### ISSUE THREAD

**Issue by meyer3a7** [BoyerChris/Team-22-Senior-Design-Project#7]

**Comment by meyer3a7** [comment]
https://www.figma.com/board/6Y57Twdn3wOassqyT6Rwjk/Team-22-Project?node-id=2-82&node-type=sticky&t=GCBIYHScPaZNYjUP-0

**Comment by meyer3a7** [comment]
Automated Backup script example:

# PowerShell example for backing up a folder
$source = "C:\SpecificFolder"
$destination = "\\NetworkDrive\Backups\SpecificFolder"
Copy-Item -Path $source -Destination $destination -Recurse -Force

**Comment by meyer3a7** [comment]
Automated Windows Software Update script example:

#Function to check for Windows updates
Write-Host "Checking for Windows updates..."
Install-Module PSWindowsUpdate -Force -AllowClobber
Import-Module PSWindowsUpdate

#Check for and install Windows Updates with Reboot
Get-WindowsUpdate -AcceptAll -Install -AutoReboot

**Comment by stanileh** [comment]
**Password Requirements Check Example:**

# _Password Check_ #

$password = Read-Host "Enter password"
if ($password.Length -ge 8 -and $password -match '[A-Z]' -and $password -match '[a-z]' -and $password -match '[0-9]' -and $password -match '[\@\$\!\%\*\?\&]') {

# _The above portion, checks if the password is 8 Characters long, if it has 1 Minimum Uppercase and Lowercase letter, if it has 1 Minimum Number, and if it has 1 Special Character_ #

# _IF IT DOES, then it informs the user that the password is valid, and lets the user log in to wherever he was entering his password._ #

Write-Host "Password is valid._"
} else {
#_IF NOT, then it informs the user that the password does not meet the requirements, we can also play with this and add values so the user understands which criteria he doesn't meet, instead of trying to figure whether the password is too short, or doesn't have a special character, etc, instead it will just inform him what criteria needs to be met._#
    Write-Host "Password does not meet requirements."
}

**Comment by stanileh** [comment]
**Password Expiration and Change Script**

#_These values store the last 10 passwords you have, (if you only have 1, or 3, or 5, last passwords then the remaining store nothing, until_ _you have changed your password at least 10 times._
$passwordHistory = @('OldPass1', 'OldPass2', 'OldPass3', 'OldPass4', 'OldPass5', 'OldPass6', 'OldPass7', 'OldPass8', 'OldPass9', 'OldPass10')
$passwordLastChanged = Get-Date "60 days ago"


#_If Password is 60 days or older, you are required to create a new password that IS NOT the same as your last 10 passwords_
if ((Get-Date) -gt $passwordLastChanged.AddDays(60)) {
    $newPassword = Read-Host "Your password has expired, enter a new password"

# _Here you are checking if the "new" password you submit was used in the last 10 passwords_
    if ($passwordHistory -contains $newPassword) {
        Write-Host "You cannot reuse the last 10 passwords."
    } else {
        Write-Host "Password is valid."

# _This is pretty neat, here you update password history and add your old password which has expired into a variable to be stored, and_ _then checked 60 days from now to ensure that you do not use the same password. This password starts at the 'OldPass1' variable, and 10_ _passwords later moves to 'OldPass10' until it is removed, and can be used again._
        $passwordHistory = $passwordHistory[1..9] + $newPassword
        $passwordLastChanged = Get-Date
    }
} else {
    Write-Host "Your password is still valid."
}
